const Resource = require("../models/Resource");
const axios = require("axios");
const BOOKING_SERVICE_URL =
  process.env.BOOKING_SERVICE_URL || "http://localhost:5003";

// Add a new resource — resourceId is auto-generated by the model
exports.addResource = async (req, res) => {
  try {
    const { name, type, capacity, location, availabilityHours } = req.body;

    if (
      !name ||
      !type ||
      !capacity ||
      !availabilityHours?.start ||
      !availabilityHours?.end
    ) {
      return res.status(400).json({
        message:
          "name, type, capacity, and availabilityHours (start & end) are required",
      });
    }

    if (capacity <= 0) {
      return res
        .status(400)
        .json({ message: "Capacity must be greater than 0" });
    }

    const resource = new Resource({
      name,
      type,
      capacity,
      location,
      availabilityHours,
    });
    await resource.save();

    res.status(201).json({ message: "Resource added successfully", resource });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Get all resources (public)
exports.getResources = async (req, res) => {
  try {
    const resources = await Resource.find();
    res.json(resources);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Get single resource by MongoDB _id (public)
exports.getResourceById = async (req, res) => {
  try {
    const resource = await Resource.findById(req.params.id);
    if (!resource)
      return res.status(404).json({ message: "Resource not found" });
    res.json(resource);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Update resource (admin only)
exports.updateResource = async (req, res) => {
  try {
    const { name, type, capacity, location, availabilityHours } = req.body;

    if (capacity !== undefined && capacity <= 0) {
      return res
        .status(400)
        .json({ message: "Capacity must be greater than 0" });
    }

    const updated = await Resource.findByIdAndUpdate(
      req.params.id,
      { name, type, capacity, location, availabilityHours },
      { new: true, runValidators: true },
    );

    if (!updated)
      return res.status(404).json({ message: "Resource not found" });

    res.json({ message: "Resource updated successfully", updated });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// Delete resource (admin only)
exports.deleteResource = async (req, res) => {
  try {
    const bookingResponse = await axios.get(
      `${BOOKING_SERVICE_URL}/booking/resource/${req.params.id}`,
    );

    if (
      Array.isArray(bookingResponse.data) &&
      bookingResponse.data.length > 0
    ) {
      return res
        .status(400)
        .json({
          message: "Resource has active bookings and cannot be deleted",
        });
    }

    const resource = await Resource.findByIdAndDelete(req.params.id);
    if (!resource)
      return res.status(404).json({ message: "Resource not found" });
    res.json({ message: "Resource deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};
